name: 'Copilot Chiste'
on: [workflow_dispatch]

permissions:
  contents: read
  copilot-requests: write

jobs:
  copilot:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5

      - name: 'Run Copilot CLI'
        uses: ./
        with:
          prompt: |
            Tell me a joke about programming in Spanish.
          agent: orchestrator
          copilot-token: ${{ github.token }}
          repo-token: ${{ github.token }}
          fail-on-error: true