name: Create Hello World Issue

on:
  workflow_call:



jobs:
  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest

    steps:
      - name: Create Hello World issue
        run: |
          gh issue create \
            --repo "${{ github.repository }}" \
            --title "Hello World" \
            --body "Hello World 🚀"
        env:
          GH_TOKEN: ${{ github.token }}
